"""Initial migration

Revision ID: 0203679dc218
Revises: 
Create Date: 2026-04-18 22:14:43.907351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0203679dc218'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_artifacts_artifact_type'), table_name='ai_artifacts')
    op.drop_index(op.f('ix_ai_artifacts_id'), table_name='ai_artifacts')
    op.drop_index(op.f('ix_ai_artifacts_lead_id'), table_name='ai_artifacts')
    op.drop_index(op.f('ix_ai_artifacts_user_id'), table_name='ai_artifacts')
    op.drop_table('ai_artifacts')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_organization_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_lead_comments_id'), table_name='lead_comments')
    op.drop_index(op.f('ix_lead_comments_organization_id'), table_name='lead_comments')
    op.drop_table('lead_comments')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_lead_memory_pins_id'), table_name='lead_memory_pins')
    op.drop_index(op.f('ix_lead_memory_pins_lead_id'), table_name='lead_memory_pins')
    op.drop_index(op.f('ix_lead_memory_pins_user_id'), table_name='lead_memory_pins')
    op.drop_table('lead_memory_pins')
    op.drop_index(op.f('ix_billing_subscriptions_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_provider_subscription_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_user_id'), table_name='billing_subscriptions')
    op.drop_table('billing_subscriptions')
    op.drop_index(op.f('ix_credits_ledger_id'), table_name='credits_ledger')
    op.drop_table('credits_ledger')
    op.drop_index(op.f('ix_email_messages_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_organization_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_tracking_token'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_owner_user_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_billing_events_external_id'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_id'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_user_id'), table_name='billing_events')
    op.drop_table('billing_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_events_user_id'), 'billing_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_billing_events_id'), 'billing_events', ['id'], unique=False)
    op.create_index(op.f('ix_billing_events_external_id'), 'billing_events', ['external_id'], unique=1)
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('lead_id', sa.INTEGER(), nullable=True),
    sa.Column('owner_user_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('company', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('segment', sa.VARCHAR(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_owner_user_id'), 'contacts', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('plan', sa.VARCHAR(), nullable=True),
    sa.Column('ai_credits', sa.INTEGER(), nullable=True),
    sa.Column('is_onboarded', sa.BOOLEAN(), nullable=True),
    sa.Column('onboarding_step', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('subscription_status', sa.VARCHAR(), server_default=sa.text("'inactive'"), nullable=True),
    sa.Column('subscription_plan', sa.VARCHAR(), nullable=True),
    sa.Column('razorpay_customer_id', sa.VARCHAR(), nullable=True),
    sa.Column('razorpay_subscription_id', sa.VARCHAR(), nullable=True),
    sa.Column('subscription_current_end', sa.DATETIME(), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('role', sa.VARCHAR(), server_default=sa.text("'owner'"), nullable=True),
    sa.Column('job_title', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('kind', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('channel', sa.VARCHAR(), nullable=True),
    sa.Column('subject', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('due_at', sa.DATETIME(), nullable=True),
    sa.Column('sequence_step', sa.INTEGER(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('assignee_user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.Column('recipient_email', sa.VARCHAR(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('tracking_token', sa.VARCHAR(), nullable=True),
    sa.Column('sent_at', sa.DATETIME(), nullable=True),
    sa.Column('opened_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_tracking_token'), 'email_messages', ['tracking_token'], unique=1)
    op.create_index(op.f('ix_email_messages_organization_id'), 'email_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_email_messages_id'), 'email_messages', ['id'], unique=False)
    op.create_table('credits_ledger',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('credits_used', sa.INTEGER(), nullable=False),
    sa.Column('credits_before', sa.INTEGER(), nullable=False),
    sa.Column('credits_after', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_ledger_id'), 'credits_ledger', ['id'], unique=False)
    op.create_table('billing_subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('plan_code', sa.VARCHAR(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('provider_subscription_id', sa.VARCHAR(), nullable=False),
    sa.Column('provider_customer_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('current_start', sa.DATETIME(), nullable=True),
    sa.Column('current_end', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_subscriptions_user_id'), 'billing_subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_provider_subscription_id'), 'billing_subscriptions', ['provider_subscription_id'], unique=1)
    op.create_index(op.f('ix_billing_subscriptions_id'), 'billing_subscriptions', ['id'], unique=False)
    op.create_table('lead_memory_pins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('is_pinned', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_memory_pins_user_id'), 'lead_memory_pins', ['user_id'], unique=False)
    op.create_index(op.f('ix_lead_memory_pins_lead_id'), 'lead_memory_pins', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_memory_pins_id'), 'lead_memory_pins', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('company', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('predicted_revenue', sa.FLOAT(), nullable=True),
    sa.Column('follow_up_date', sa.VARCHAR(), nullable=True),
    sa.Column('health_score', sa.FLOAT(), nullable=True),
    sa.Column('health_status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_activity_at', sa.DATETIME(), nullable=True),
    sa.Column('relationship_score', sa.INTEGER(), server_default=sa.text('(50)'), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('owner_user_id', sa.INTEGER(), nullable=True),
    sa.Column('segment', sa.VARCHAR(), server_default=sa.text("'general'"), nullable=True),
    sa.Column('tags', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=1)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('lead_comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('author_name', sa.VARCHAR(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_comments_organization_id'), 'lead_comments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lead_comments_id'), 'lead_comments', ['id'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_organization_id'), 'email_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_table('ai_artifacts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('artifact_type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=False),
    sa.Column('context_snapshot', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_artifacts_user_id'), 'ai_artifacts', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_artifacts_lead_id'), 'ai_artifacts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_ai_artifacts_id'), 'ai_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_ai_artifacts_artifact_type'), 'ai_artifacts', ['artifact_type'], unique=False)
    # ### end Alembic commands ###
